FROM kpengboy/trisquel
RUN apt-get update -qq && apt-get install -y \
  autoconf \
  build-essential \
  curl


# PHP-5.4.9
RUN curl -so php-5.4.9.tar.bz2 \
    http://museum.php.net/php5/php-5.4.9.tar.bz2
RUN tar xjf php-5.4.9.tar.bz2
RUN apt-get update -qq && apt-get install -y libxml2-dev
RUN cd php-5.4.9 && \
    ./configure --prefix=/opt/php-5.4.9 \
      --enable-debug \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.4.9*
RUN strip /opt/php-5.4.9/bin/php

# PHP-5.5.38
RUN curl -so php-5.5.38.tar.bz2 \
    http://www.php.net/distributions/php-5.5.38.tar.bz2
RUN tar xjf php-5.5.38.tar.bz2
RUN apt-get update -qq && apt-get install -y libxml2-dev
RUN cd php-5.5.38 && \
    ./configure --prefix=/opt/php-5.5.38 \
      --enable-debug \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.5.38*
RUN strip /opt/php-5.5.38/bin/php

# PHP-5.6.28
RUN curl -so php-5.6.28.tar.bz2 \
    http://www.php.net/distributions/php-5.6.28.tar.bz2
RUN tar xjf php-5.6.28.tar.bz2
RUN apt-get update -qq && apt-get install -y libxml2-dev
RUN cd php-5.6.28 && \
    ./configure --prefix=/opt/php-5.6.28 \
      --enable-debug \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.6.28*
RUN strip /opt/php-5.6.28/bin/php

# PHP-7.0.13
RUN curl -so php-7.0.13.tar.bz2 \
    http://www.php.net/distributions/php-7.0.13.tar.bz2
RUN tar xjf php-7.0.13.tar.bz2
RUN cd php-7.0.13 && \
    ./configure --prefix=/opt/php-7.0.13 \
      --enable-debug \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-7.0.13*
RUN rm /opt/php-7.0.13/bin/phpdbg
RUN strip /opt/php-7.0.13/bin/php

# PHP-7.1.0
RUN curl -so php-7.1.0.tar.bz2 \
    http://www.php.net/distributions/php-7.1.0.tar.bz2
RUN tar xjf php-7.1.0.tar.bz2
RUN cd php-7.1.0 && \
    ./configure --prefix=/opt/php-7.1.0 \
      --enable-debug \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-7.1.0*
RUN rm /opt/php-7.1.0/bin/phpdbg
RUN strip /opt/php-7.1.0/bin/php

# TODO: install multiple geos versions
RUN apt-get update -qq && apt-get install -y libgeos-dev
