FROM docker.io/kpengboy/trisquel
RUN apt-get update -qq && apt-get install -y \
  autoconf \
  build-essential \
  cmake \
  curl


# PHP-5.4.9
RUN curl -sLo php-5.4.9.tar.bz2 \
    http://museum.php.net/php5/php-5.4.9.tar.bz2
RUN tar xjf php-5.4.9.tar.bz2
RUN cd php-5.4.9 && \
    ./configure --prefix=/opt/php-5.4.9 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.4.9*
RUN strip /opt/php-5.4.9/bin/php

# PHP-5.5.38
RUN curl -sLo php-5.5.38.tar.bz2 \
    http://www.php.net/distributions/php-5.5.38.tar.bz2
RUN tar xjf php-5.5.38.tar.bz2
RUN cd php-5.5.38 && \
    ./configure --prefix=/opt/php-5.5.38 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.5.38*
RUN strip /opt/php-5.5.38/bin/php

# PHP-5.6.28
RUN curl -sLo php-5.6.28.tar.bz2 \
    http://www.php.net/distributions/php-5.6.28.tar.bz2
RUN tar xjf php-5.6.28.tar.bz2
RUN cd php-5.6.28 && \
    ./configure --prefix=/opt/php-5.6.28 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-5.6.28*
RUN strip /opt/php-5.6.28/bin/php

# PHP-7.0.13
RUN curl -sLo php-7.0.13.tar.bz2 \
    http://www.php.net/distributions/php-7.0.13.tar.bz2
RUN tar xjf php-7.0.13.tar.bz2
RUN cd php-7.0.13 && \
    ./configure --prefix=/opt/php-7.0.13 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-7.0.13*
RUN rm /opt/php-7.0.13/bin/phpdbg
RUN strip /opt/php-7.0.13/bin/php

# PHP-7.1.0
RUN curl -sLo php-7.1.0.tar.bz2 \
    http://www.php.net/distributions/php-7.1.0.tar.bz2
RUN tar xjf php-7.1.0.tar.bz2
RUN cd php-7.1.0 && \
    ./configure --prefix=/opt/php-7.1.0 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-7.1.0*
RUN rm /opt/php-7.1.0/bin/phpdbg
RUN strip /opt/php-7.1.0/bin/php

# PHP-7.4.30
RUN curl -sLo php-7.4.30.tar.bz2 \
    http://www.php.net/distributions/php-7.4.30.tar.bz2
RUN tar xjf php-7.4.30.tar.bz2
RUN cd php-7.4.30 && \
    ./configure --prefix=/opt/php-7.4.30 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-7.4.30*
RUN rm /opt/php-7.4.30/bin/phpdbg
RUN strip /opt/php-7.4.30/bin/php

# PHP-8.1.10
RUN curl -sLo php-8.1.10.tar.bz2 \
    http://www.php.net/distributions/php-8.1.10.tar.bz2
RUN tar xjf php-8.1.10.tar.bz2
RUN cd php-8.1.10 && \
    ./configure --prefix=/opt/php-8.1.10 \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-8.1.10*
RUN rm /opt/php-8.1.10/bin/phpdbg
RUN strip /opt/php-8.1.10/bin/php


# GEOS-3.4.3
RUN curl -sLo geos-3.4.3.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.4.3.tar.bz2
RUN tar xjf geos-3.4.3.tar.bz2
RUN cd geos-3.4.3 && \
    ./configure --prefix=/opt/geos-3.4.3 \
      --disable-swig \
      --disable-static \
    && make install-strip
RUN cd .. && rm -rf geos-3.4.3*

# GEOS-3.5.2
RUN curl -sLo geos-3.5.2.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.5.2.tar.bz2
RUN tar xjf geos-3.5.2.tar.bz2
RUN cd geos-3.5.2 && \
    ./configure --prefix=/opt/geos-3.5.2 \
      --disable-swig \
      --disable-static \
    && make install-strip
RUN cd .. && rm -rf geos-3.5.2*

# GEOS-3.6.6
RUN curl -sLo geos-3.6.6.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.6.6.tar.bz2
RUN tar xjf geos-3.6.6.tar.bz2
RUN cd geos-3.6.6 && \
    ./configure --prefix=/opt/geos-3.6.6 \
      --disable-swig \
      --disable-static \
    && make install-strip
RUN cd .. && rm -rf geos-3.6.6*

# GEOS-3.7.5
RUN curl -sLo geos-3.7.5.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.7.5.tar.bz2
RUN tar xjf geos-3.7.5.tar.bz2
RUN cd geos-3.7.5 && \
    ./configure --prefix=/opt/geos-3.7.5 \
      --disable-swig \
      --disable-static \
    && make install-strip
RUN cd .. && rm -rf geos-3.7.5*

# GEOS-3.8.4
RUN curl -sLo geos-3.8.4.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.8.4.tar.bz2
RUN tar xjf geos-3.8.4.tar.bz2
RUN cd geos-3.8.4 && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-3.8.4 \
    && make install
RUN cd .. && rm -rf geos-3.8.4*

# GEOS-3.9.6
RUN curl -sLo geos-3.9.6.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.9.6.tar.bz2
RUN tar xjf geos-3.9.6.tar.bz2
RUN cd geos-3.9.6 && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-3.9.6 \
    && make install
RUN cd .. && rm -rf geos-3.9.6*

# GEOS-3.10.7
RUN curl -sLo geos-3.10.7.tar.bz2 \
    http://download.osgeo.org/geos/geos-3.10.7.tar.bz2
RUN tar xjf geos-3.10.7.tar.bz2
RUN cd geos-3.10.7 && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-3.10.7 \
    && make install
RUN cd .. && rm -rf geos-3.10.7*

ARG GEOSVERSION=3.11.5
RUN curl -sLo geos-${GEOSVERSION}.tar.bz2 \
    http://download.osgeo.org/geos/geos-${GEOSVERSION}.tar.bz2
RUN tar xjf geos-${GEOSVERSION}.tar.bz2
RUN cd geos-${GEOSVERSION} && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-${GEOSVERSION} \
    && make install
RUN cd .. && rm -rf geos-${GEOSVERSION}*

ARG GEOSVERSION=3.12.3
RUN curl -sLo geos-${GEOSVERSION}.tar.bz2 \
    http://download.osgeo.org/geos/geos-${GEOSVERSION}.tar.bz2
RUN tar xjf geos-${GEOSVERSION}.tar.bz2
RUN cd geos-${GEOSVERSION} && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-${GEOSVERSION} \
    && make install
RUN cd .. && rm -rf geos-${GEOSVERSION}*

ARG GEOSVERSION=3.13.1
RUN curl -sLo geos-${GEOSVERSION}.tar.bz2 \
    http://download.osgeo.org/geos/geos-${GEOSVERSION}.tar.bz2
RUN tar xjf geos-${GEOSVERSION}.tar.bz2
RUN cd geos-${GEOSVERSION} && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-${GEOSVERSION} \
    && make install
RUN cd .. && rm -rf geos-${GEOSVERSION}*

ARG GEOSVERSION=3.14.1
RUN curl -sLo geos-${GEOSVERSION}.tar.bz2 \
    http://download.osgeo.org/geos/geos-${GEOSVERSION}.tar.bz2
RUN tar xjf geos-${GEOSVERSION}.tar.bz2
RUN cd geos-${GEOSVERSION} && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/geos-${GEOSVERSION} \
    && make install
RUN cd .. && rm -rf geos-${GEOSVERSION}*

# Debian GNU/Linux 13 (trixie) ships PHP-8.4.16
ARG PHPVERSION=8.4.16
RUN curl -sLo php-${PHPVERSION}.tar.bz2 \
    http://www.php.net/distributions/php-${PHPVERSION}.tar.bz2
RUN tar xjf php-${PHPVERSION}.tar.bz2
RUN cd php-${PHPVERSION} && \
    ./configure --prefix=/opt/php-${PHPVERSION} \
      --enable-debug \
      --disable-all \
      --disable-cgi \
      --disable-dom \
      --disable-libxml \
      --disable-simplexml \
      --disable-xml \
      --disable-xmlreader \
      --disable-xmlwriter \
      --without-pear && \
    make install
RUN cd .. && rm -rf php-${PHPVERSION}*
RUN rm /opt/php-${PHPVERSION}/bin/phpdbg
RUN strip /opt/php-${PHPVERSION}/bin/php
