# See https://woodpecker-ci.org/docs/intro

when:
  event: [push, pull_request]

matrix:
  PHP_BIN:
    - /opt/php-7.0.13/bin/
    - /opt/php-7.1.0/bin/
    - /opt/php-7.4.30/bin/
    - /opt/php-8.1.10/bin/
    - /opt/php-8.4.16/bin/
  GEOS_BIN:
    - /opt/geos-3.4.3/bin/
    - /opt/geos-3.5.2/bin/
    - /opt/geos-3.6.6/bin/
    - /opt/geos-3.7.5/bin/
    - /opt/geos-3.8.4/bin/
    - /opt/geos-3.9.6/bin/
    - /opt/geos-3.10.7/bin/
    - /opt/geos-3.11.5/bin/
    - /opt/geos-3.12.3/bin/
    - /opt/geos-3.13.1/bin/
    - /opt/geos-3.14.1/bin/

steps:
  - name: build
    image: docker.osgeo.org/geos/php-build-test:trisquel
    pull: true
    commands:
      # See https://github.com/libgeos/geos/pull/1436
      - export LD_LIBRARY_PATH=${GEOS_BIN}/../lib:$${LD_LIBRARY_PATH}
      - echo $${LD_LIBRARY_PATH}
      - export PATH=${PHP_BIN}:${GEOS_BIN}:$${PATH}
      - phpize
      - ./configure
      - make
      - make check
